name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest ./app

    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/flask-app:latest'

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Set up Kubeconfig
    #   run: |
    #     mkdir -p $HOME/.kube
    #     echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config

    # - name: Deploy to Kubernetes using Helm
    #   run: |
    #     helm upgrade --install flask-app ./charts/flask-app --namespace default

    # - name: Install Minikube
    #   run: |
    #     curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    #     sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Install and Configure Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker --wait=all
        minikube addons enable ingress
        minikube update-context


    # - name: Start Minikube
    #   run: |
    #     minikube start --driver=docker --wait=all
    #     minikube addons enable ingress

    # - name: Configure kubectl to use Minikube context
    #   run: |
    #     echo "Setting up kubeconfig"
    #     mkdir -p $HOME/.kube
    #     minikube update-context
    
    # - name: Configure kubectl
    #   run: |
    #     echo "Setting up kubeconfig"
    #     mkdir -p $HOME/.kube
    #     cp $HOME/.kube/config $HOME/.kube/config.bak || true
    #     minikube kubeconfig > $HOME/.kube/config

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy App with Helm
      run: |
        helm upgrade --install flask-app ./charts/flask-app --namespace default --create-namespace

    - name: Check Pods
      run: |
        kubectl get pods -A

    - name: Wait for Deployment
      run: |
        kubectl rollout status deployment/flask-app -n default --timeout=180s

    - name: Get Service Info
      run: |
        minikube service list