name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  Docker-Build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest ./app

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  Security-check:
    runs-on: self-hosted
    needs: Docker-Build
    
    steps:
    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/flask-app:latest'
            
  Minikube-install-and-configure:
    runs-on: self-hosted
    needs: Security-check

    steps:
    - name: Install and Configure Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker --wait=all
        minikube addons enable ingress
        minikube update-context

    - name: Wait for Ingress Controller to be Ready
      run: |
        echo "Waiting for ingress-nginx-controller to become ready..."
        kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=120s

    - name: Delete Existing Ingress (if any)
      run: |
        kubectl delete ingress flask-app --ignore-not-found
  
  Helm-installation:
    runs-on: self-hosted
    needs: Minikube-install-and-configure

    steps:
    - name: Remove Helm Release (if exists)
      run: |
        helm uninstall flask-app || true

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  deploy_to_kubernetes:
    runs-on: self-hosted
    needs: Helm-installation

    steps:
    - name: Deploy App with Helm
      run: |
        helm upgrade --install flask-app ./charts/flask-app --namespace default --create-namespace

    - name: Wait for Deployment
      run: |
        kubectl rollout status deployment/flask-app -n default --timeout=600s

    - name: Pause for 2 minutes
      run: sleep 120

    - name: Check Pods
      run: |
        kubectl get pods -n default

    - name: Check service
      run: |
        kubectl get svc -A

    - name: Get Service Info
      run: |
        minikube service list
